// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InitBuffers

type TimerState = int8

const (
	TimerStateStopped TimerState = 0
	TimerStatePaused  TimerState = 1
	TimerStateStarted TimerState = 2
	TimerStateExpired TimerState = 3
)

var EnumNamesTimerState = map[TimerState]string{
	TimerStateStopped: "Stopped",
	TimerStatePaused:  "Paused",
	TimerStateStarted: "Started",
	TimerStateExpired: "Expired",
}
