// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WalBuffers

type Command = int8

const (
	Commandwal  Command = 0
	Commandinit Command = 1
)

var EnumNamesCommand = map[Command]string{
	Commandwal:  "wal",
	Commandinit: "init",
}
