// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WalBuffers

type ObjectType = int8

const (
	ObjectTypeplayer     ObjectType = 0
	ObjectTypeenemy_mech ObjectType = 1
	ObjectTyperock       ObjectType = 2
	ObjectTypexelon      ObjectType = 3
	ObjectTypemissile    ObjectType = 4
	ObjectTypespore      ObjectType = 5
)

var EnumNamesObjectType = map[ObjectType]string{
	ObjectTypeplayer:     "player",
	ObjectTypeenemy_mech: "enemy_mech",
	ObjectTyperock:       "rock",
	ObjectTypexelon:      "xelon",
	ObjectTypemissile:    "missile",
	ObjectTypespore:      "spore",
}
