// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WalBuffers

type ObjectType = int8

const (
	ObjectTypeplayer     ObjectType = 0
	ObjectTypemissile    ObjectType = 1
	ObjectTyperock       ObjectType = 2
	ObjectTypeenemy_mech ObjectType = 3
	ObjectTypexelon      ObjectType = 4
)

var EnumNamesObjectType = map[ObjectType]string{
	ObjectTypeplayer:     "player",
	ObjectTypemissile:    "missile",
	ObjectTyperock:       "rock",
	ObjectTypeenemy_mech: "enemy_mech",
	ObjectTypexelon:      "xelon",
}
