// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WalBuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ObjectLog struct {
	_tab flatbuffers.Table
}

func GetRootAsObjectLog(buf []byte, offset flatbuffers.UOffsetT) *ObjectLog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ObjectLog{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ObjectLog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ObjectLog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ObjectLog) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectLog) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ObjectLog) Type() ObjectType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectLog) MutateType(n ObjectType) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func (rcv *ObjectLog) Times(obj *TimeLog, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ObjectLog) TimesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ObjectLogStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ObjectLogAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func ObjectLogAddType(builder *flatbuffers.Builder, type_ int8) {
	builder.PrependInt8Slot(1, type_, 0)
}
func ObjectLogAddTimes(builder *flatbuffers.Builder, times flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(times), 0)
}
func ObjectLogStartTimesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ObjectLogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
